name-template: v$NEXT_PATCH_VERSION 🌈
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: chore
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Summary  

  ## Changes

  $CHANGES
  
  ## Contributors
  We appreciate all of our contributors that have made this release possible, thank you!
  
  $CONTRIBUTORS
