version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get -y install python3-pip
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - make build
      - echo Running ci tests
      - make test-ci
  post_build:
    commands:
      - echo Collecting coverage information
      - apt-get -y install git
      - pip3 install coveralls==1.5.1
      - sed -i -e "s@/app/@$PWD/@g" ./tests/coverage/.coverage
      - cat ./tests/coverage/.coverage
      - coveralls
