version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - make build
      - echo Running ci tests
      - make test-ci