FROM qspprotocol/securify@sha256:ad5637f7662aa80ca8c4716b7cb3a2999cdcb03d78daf71ba6ae13d982fd5b2b
RUN apt-get update
RUN apt-get install wget

RUN apt-get install -y libtool
RUN apt-get install -y vim
RUN apt-get install -y python-pip
RUN apt-get install -y python3-pip

# Install requirement for usolc
RUN pip3 install node-semver==0.6.1

# Install solc
## Create solc-versions directory
RUN mkdir /usr/local/bin/solc-versions

# Create a directory to host testing files
RUN mkdir /app
WORKDIR /app
COPY . .

RUN chmod +x run_tests

# usolc setup
# Running the solc download
RUN chmod +x ./usolc/solc_download
RUN ./usolc/solc_download

# Copying usolc scripts
RUN cp ./usolc/usolc.py /usr/local/bin/solc-versions/usolc.py
RUN cp -r ./usolc/exceptions /usr/local/bin/solc-versions/exceptions
RUN cp ./usolc/solc_version_list /usr/local/bin/solc-versions/solc_version_list
RUN cp ./usolc/solc /usr/local/bin/solc
RUN chmod +x /usr/local/bin/solc

WORKDIR /
ENTRYPOINT ["java", "-Xmx16G", "-jar", "/securify_jar/securify.jar"]

