#!/bin/bash
####################################################################################################
#                                                                                                  #
# (c) 2019 Quantstamp, Inc. All rights reserved.  This content shall not be used, copied,          #
# modified, redistributed, or otherwise disseminated except to the extent expressly authorized by  #
# Quantstamp for credentialed users. This content and its use are governed by the Quantstamp       #
# Demonstration License Terms at <https://s3.amazonaws.com/qsp-protocol-license/LICENSE.txt>.      #
#                                                                                                  #
####################################################################################################

SOLCVERSION=()

while read -r line || [[ -n "$line" ]]; do
    SOLCVERSION+=("$line")
done < usolc/solc_version_list

LIST_SOLC_STATIC_LINUX="0.4.11 0.4.12 0.4.13 0.4.14 0.4.15 0.4.16 0.4.17 0.4.18 0.4.19 0.4.20 "\
"0.4.21 0.4.22 0.4.23 0.4.24 0.4.25 0.5.0 0.5.1 0.5.2 0.5.3 0.5.4"

LIST_SOLC="0.4.10"

LIST_TAR_COMPILE_SOLC="0.4.9 0.4.8 0.4.7 0.4.6 0.4.5"

apk add cmake

apk add gcc

for version in "${SOLCVERSION[@]}"
do
    if echo ${LIST_SOLC_STATIC_LINUX} | grep -w ${version} > /dev/null; then
        echo "Downloading solc-$version"
        link="https://github.com/ethereum/solidity/releases/download/v$version/solc-static-linux"
        wget ${link}
        chmod +x solc-static-linux
        mv solc-static-linux "/usr/local/bin/solc-versions/solc-$version"
    elif echo ${LIST_SOLC} | grep -w ${version} > /dev/null; then
        echo "Downloading solc-$version"
        link="https://github.com/ethereum/solidity/releases/download/v$version/solc"
        wget ${link}
        chmod +x solc
        mv solc "/usr/local/bin/solc-versions/solc-$version"
    elif echo ${LIST_TAR_COMPILE_SOLC} | grep -w ${version} > /dev/null; then
        echo "Moving solc-$version"
        chmod +x "./usolc/compiled_solc/solc-$version"
        mv "./usolc/compiled_solc/solc-$version" "/usr/local/bin/solc-versions/solc-$version"
    fi
done
