#!/bin/bash
####################################################################################################
#                                                                                                  #
# (c) 2019 Quantstamp, Inc. All rights reserved.  This content shall not be used, copied,          #
# modified, redistributed, or otherwise disseminated except to the extent expressly authorized by  #
# Quantstamp for credentialed users. This content and its use are governed by the Quantstamp       #
# Demonstration License Terms at <https://s3.amazonaws.com/qsp-protocol-license/LICENSE.txt>.      #
#                                                                                                  #
####################################################################################################

SOLCVERSION=()

while read -r line || [[ -n "$line" ]]; do
    SOLCVERSION+=("$line")
done < usolc/solc_version_list


for version in "${SOLCVERSION[@]}"
do
    echo "Downloading solc-$version"
    link="https://github.com/ethereum/solidity/releases/download/v$version/solc-static-linux"
    wget $link
    chmod +x solc-static-linux
    mv solc-static-linux "/usr/local/bin/solc-versions/solc-$version"
done
